name: Android CI
#   STEP 1 : PREPARE
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0'
jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew testDebug

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.EWA_KEY_APP_NAME }}
          keyPassword: ${{ secrets.EWA_KEY_PASSWORD }}
          
#   STEP 2 : Upload the Artifact
  upload:
    needs: [ build ]
    name: Upload the signed artifact
    runs-on: self-hosted
    steps:
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: signed_app_bundle
          path: app/build/outputs/bundle/release/app-release.aab
